-- 코드를 입력하세요
SELECT DISTINCT O.USER_ID, O.PRODUCT_ID
FROM ONLINE_SALE O, ONLINE_SALE J
WHERE O.PRODUCT_ID = J.PRODUCT_ID AND O.USER_ID = J.USER_ID AND O.SALES_DATE < J.SALES_DATE
ORDER BY O.USER_ID, O.PRODUCT_ID DESC;