SELECT DISTINCT O.ITEM_ID as ITEM_ID, 
O.ITEM_NAME as ITEM_NAME, 
O.RARITY as RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T on T.PARENT_ITEM_ID = I.ITEM_ID
JOIN ITEM_INFO O on T.ITEM_ID = O.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY ITEM_ID desc
